language: node_js
node_js:
  - stable
script:
  - "npm run test"
  - "npm run build"
  - "find public -name '*.map' -delete"
deploy:
  skip_cleanup: true
  provider: surge
  project: public
  domain: 2018.cascadiajs.com
  on: master
